name: User catalogue

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build & Test & Package with Maven
        run: |
          mvn -Dspring.profiles.active=prod package -B --file pom.xml
      - name: Build a Docker image
        run: |
          mkdir target/dependency
          (cd target/dependency; jar -xf ../*.jar)
          docker build . -t ${{ secrets.DOCKERHUB_USERNAME }}/rso-user-catalogue:$(git rev-parse --short "$GITHUB_SHA")
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/rso-user-catalogue:$(git rev-parse --short "$GITHUB_SHA")
      - name: Setup Kubectl
        uses: azure/setup-kubectl@v1
      - name: Setup AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_TEST }}
          resource-group: ${{ secrets.RESOURCE_GROUP_TEST}}
          cluster-name: rso23-test
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/user-catalogue-deployment user-catalogue=${{ secrets.DOCKERHUB_USERNAME }}/rso-user-catalogue:$(git rev-parse --short "$GITHUB_SHA")